### ISSUE TITLE
Failure while rendering templates with components

### ISSUE THREAD

**Issue by balek** [psirenny/derby-render#1]
Derby components call some methods of `Page` object, which isn't defined. Maybe it's better not to use derby-templates directly, but use `staticRender` with fake `req` and `res`?

**Comment by psirenny** [comment]
You raise a good point. I hadn't considered static rendering but it is a better solution. I was finding the lack of a `req` and therefore middleware, a little frustrating. I'll have some time over the weekend to work on this.

**Comment by mattbrun** [comment]
hi @psirenny , do you have news on this? thanks
I tried to dig into the code very very quickly in order to see if I was able to get a quick solution, but I couldn't find any...

**Comment by psirenny** [comment]
Sorry, I went dark for a while. I took your advice @balek and switched to static rendering. I bumped the version to 2.0 and listed other related changes in the readme.

**Comment by balek** [comment]
Wouldn't it be even better to directly [use page.get](https://github.com/derbyjs/derby/blob/master/lib/Page.server.js#L42-L43)?
[Page view redefinition](https://github.com/psirenny/derby-email/blob/master/lib/index.js#L30) in derby-email makes it impossible to use same derby app for both mail and pages.
Do you agree? I can try to patch derby-render and derby-email myself and make a PR.
